### ISSUE TITLE
Producing deb files

### ISSUE THREAD

**Issue by fser** [JackSlateur/backuppc4#1]
Hi,

I've been trying to setup a clean github repo for backuppc4, backuppc-xs and rsync-bcp. For one of those, it was hard to setup a clean build environement (I'm a beginer in that topic).

You have obviously produced debian packages, can you provide me makefile / script so that I can automate the build from sources?

Thanks!
FYI, my repos are https://github.com/fser/BackupPC, https://github.com/fser/rsync-bpc and https://github.com/fser/BackupPC-XS.

**Comment by JackSlateur** [comment]
The Deb sources are included : see https://github.com/clobrother/backuppc4/tree/master/rsync-bpc/rsync-bpc-3.0.9.3/debian, https://github.com/clobrother/backuppc4/tree/master/BackupPC-4.0.0alpha3/backuppc-4.0.0alpha3/debian & https://github.com/clobrother/backuppc4/tree/master/BackupPC-XS-0.30/backuppc-xs-0.30/debian

**Comment by fser** [comment]
Thanks, gonna have a look on that then!
I'm not that familiar with debian packaging yet.
